spring.application.name=promptly

ai.base-url=https://openrouter.ai/api/v1
ai.api-key=${AI_API_KEY}
ai.model=openai/gpt-4o-mini

# Retry
resilience4j.retry.instances.aiClient.max-attempts=3
resilience4j.retry.instances.aiClient.wait-duration=1s
resilience4j.retry.instances.aiClient.enable-exponential-backoff=true
resilience4j.retry.instances.aiClient.exponential-backoff-multiplier=2
resilience4j.retry.instances.aiClient.retry-exceptions=org.example.promptly.exception.RetryableHttpException
resilience4j.retry.instances.aiClient.ignore-exceptions=org.example.promptly.exception.NonRetryableHttpException
# Circuit Breaker
resilience4j.circuitbreaker.instances.aiClient.sliding-window-size=10
resilience4j.circuitbreaker.instances.aiClient.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.aiClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.aiClient.wait-duration-in-open-state=5s
# Sätt ordningen, CircuitBreaker utanpå Retry
resilience4j.circuitbreaker.circuitBreakerAspectOrder=1
resilience4j.retry.retryAspectOrder=2