spring.application.name=promptly

ai.base-url=https://openrouter.ai/api/v1
#ai.base-url=http://fel-url.example.com
ai.api-key=${AI_API_KEY}
ai.model=openai/gpt-4o-mini

resilience4j.retry.instances.aiClient.max-attempts=3
resilience4j.retry.instances.aiClient.wait-duration=1s
resilience4j.retry.instances.aiClient.enable-exponential-backoff=true
resilience4j.retry.instances.aiClient.exponential-backoff-multiplier=2

logging.level.io.github.resilience4j=DEBUG